config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[new create edit update delete]
  resources :posts
  resources :sessions, only: %i[new create]
  resources :comments, only: %i[create]

  get '/', to: "posts#index"

  get '/home', to: "posts#home"

  get '/comment', to: "posts#index"

  get '/sessions/account', to: "sessions#account", as: 'account'

  get '/sessions/', to: "sessions#new"

  post '/posts/support/:id', to: "posts#support", as: "support"

  post '/users/follow/:id', to: "users#follow", as: "follow"

  delete '/sessions/delete', to: "sessions#delete"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  mount_uploader :image, ImageUploader

  validates :content, presence: true, length: {maximum: 3000 }

  belongs_to :user
  has_many :post_likes
  has_many :users, through: :post_likes

  has_many :comments

  paginates_per 24


  def amt_likes
    self.users.count
  end

  def recent_comments
    return comments.first(5)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[show edit update support destroy]

  def index
    @posts = Post.order('created_at DESC').page params[:page]
  end

  def home
    @user = User.find(session[:user_id])
    ids = @user.following.collect {|u| u.id}
    @posts = Post.where(user_id: ids).order('created_at DESC').page params[:page]
  end

  def new
    @user = User.find(session[:user_id])
    @post = Post.new
  end

  def create
    params[:post][:user_id] = session[:user_id]
    @post = Post.create(post_params)
    if @post.valid?
      redirect_to posts_path
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post_user = User.find(@post.user.id)
    @posts = Post.where("user_id = #{@post_user.id}").order('created_at DESC').limit(5)
    @comment = Comment.new
    @comments = Comment.where("post_id = #{@post.id}").order('created_at DESC')
    if session[:user_id]
      @session_user = User.find(session[:user_id])
      if @session_user.find_like(@post.id).empty?
        @like_message = "like"
      else
        @like_message = "liked"
      end
      if @session_user.find_follow(@post_user.id)
        @follow_message = "unfollow #{@post_user.username}"
      else
        @follow_message = "follow #{@post_user.username}"
      end
    end
  end

  def edit
    @session_user = User.where("id = #{session[:user_id]}").first
    if @session_user && @session_user.password_digest == @post.user.password_digest
      render :edit
    else
      redirect_to account_path
    end
  end

  def update
    @post.update(post_params)
    if @post.valid?
      redirect_to @post
    else
      flash[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to account_path
  end

  def support
    @session_user = User.find(session[:user_id])

    respond_to do |format|
      if @session_user.find_like(params[:id]).empty?
        @session_user.like_post(params[:id])
        format.html {redirect_to(@post)}
        format.js
        format.json {render json: @post}
        # redirect_back(fallback_location: posts_path)      
      else
        @session_user.unlike_post(params[:id])
        # redirect_back(fallback_location: posts_path)
        format.html {redirect_to(@post)}
        format.js
        format.json {render json: @post}
      end
    end
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:user_id, :title, :content, :image)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<%= form_for @comment, html: {class:"ui large form error"} do |f| %>

<%if flash[:errors] %>
  <div class="ui error message">
      <% flash[:errors].each do |err| %>
      <ul class="list">
        <li><%= err %></li>
      </ul>
      <% end %>
  </div>
<% end %>
<div style="border-bottom: solid 1px orange; padding-bottom:10px">
  <div style="display:flex; flex-direction: row;">
    <%= f.text_area :content, rows: 1,  class: "ui input" %>
    <%= f.submit "post", class: "ui mini orange submit button", style:"max-height: 50px; padding: 1;"%>
  </div>
</div>
<%= hidden_field_tag "comment[user_id]", session[:user_id] %>
<%= hidden_field_tag "comment[post_id]", @post.id %>
<% end %>

app/views/posts/_form.html.erb
<div class="ui very padded text container segment orange">
  <div class="ui middle aligned center aligned grid">
    <div class="column">
      <h2 class="ui orange header">
        <div class="content">
          Post
        </div>
      </h2>

      <%= form_for @post, html: {class:"ui large form error"} do |f| %>

      <%if flash[:errors] %>
        <div class="ui error message">
            <% flash[:errors].each do |err| %>
            <ul class="list">
              <li><%= err %></li>
            </ul>
            <% end %>
        </div>
      <% end %>

        <%= f.file_field :image %>
        
      <div class="ui segment stackable">
        <%= f.label :content, class: "field" %>
          <%= f.text_area :content, class: "ui input" %>
      </div>
      <%= f.submit "Create Post", class: "ui fluid large orange submit button"%>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_posts.html.erb
<div class="ui text segment orange">
    <div class="ui one stackable cards">
      <% @posts.each do |post| %>
      <div class="card">
        <div class="content">
          <span class="">
            <i class="bottom floated like icon red"></i>
            <%= post.amt_likes %>
          </span>
          <span class="right floated author">
            <%= image_tag "manpoemlogo.png", class: "ui avatar image"%>
            <%= post.user.username %>
          </span>
        </div>
        <a href=<%="/posts/#{post.id}"%> class="image small">
              <img src="<%= post.image %>">
        </a>
        <div class="content">
          <span style="font-weight: bold;"><%= post.user.username %> </span>
          <%= post.content %>
        </div>


          
        <div class="content">
          <% if post.recent_comments.length > 0 %>
          <% post.comments.last(2).each do |comment| %>
          <div style="margin-top: 1px; margin-bottom: 1px;">
            <span style="font-weight: bold;"> <%= comment.user.username %> </span>
            <%= comment.content %>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>

app/views/posts/edit.html.erb
<%= render "form" %>

app/views/posts/home.html.erb
<div class="eight wide column">
    <%= render "posts" %>
        <div class="ui padded text segment center aligned inverted black">
          <%= link_to_previous_page @posts, 'Previous Page' %> ||
          <%= page_entries_info @posts %> ||
          <%= link_to_next_page @posts, 'Next Page' %>
        </div>
</div>

app/views/posts/index.html.erb
  <div class="column">
    <%= render "posts" %>
        <div class="ui padded text segment center aligned inverted black">
          <%= link_to_previous_page @posts, 'Previous Page' %> ||
          <%= page_entries_info @posts %> ||
          <%= link_to_next_page @posts, 'Next Page' %>
        </div>
  </div>

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/show.html.erb
<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |err| %>
      <li>
        <%= err %>
      </li>
    </ul>
  <% end %>
<% end %>

<div class="three wide column">
  <div class="ui card">
    <div class="image dimmable">
      <div class="ui blurring inverted dimmer transition hidden">
        <div class="content">
          <div class="center">
            <div class="ui teal button">
              Follow
            </div>
          </div>
        </div>
      </div>
      <%= image_tag "manpoemlogo.png", class: "small"%>
    </div>
    <div class="content">
      <div class="header">
        <%= @post.user.username %>
      </div>
      <div class="meta">
        <%= @post.user.description %>
      </div>
    </div>
    <% if session[:user_id]%>
      <div class="extra content">
          <%= button_to @follow_message, follow_path(@post.user.id), method: :post, class: "ui fluid basic button"%>
      </div>
    <% end %>
  </div>
</div>
<div class="eight wide column">
  <div class="ui card fluid">
    <div class="content">
        <%= @post.content %>
    </div>
    <div class="image">
      <img src="<%= @post.image %>">
    </div>
    <div class="extra content">
      <span class="">
        <div class="ui labeled button" tabindex="0">
          <% if session[:user_id]%>
            <%= button_to @like_message, support_path(@post.id), method: :post, class: "ui red button" %>
          <% end %>
          <a class="ui basic label">
            <%= @post.amt_likes%> likes
          </a>
        </div>
      </span>
      <span class="right floated author">
        <%= image_tag "manpoemlogo.png", class: "ui avatar image"%>
        <%= @post.user.username %>
      </span>
    </div>
     <% if session[:user_id]%>
      <%= render "comment" %>
    <% end %>
      <div style="margin: 10px">
        <%if @comments.length > 0 %>
        <% @comments.reverse.each do |comment| %>
        <div style="margin: 1px">
          <span style="font-weight: bold;"><%= comment.user.username %> </span>
          <%= comment.content %>
        </div>
        <% end %>
        <% end %>
      </div>
  </div>
</div>
<div class="five wide column" style="padding 0px; max-height:100vh; overflow:auto;">
  <h3 class="ui top attached header center aligned inverted">
    Recent posts by <%= @post.user.username %>
  </h3>
  <div>
    <div>
      <%= render "posts" %>
    </div>
  </div>
</div>

app/views/posts/support.js.erb
$('.show_amt_likes').html("<%= @post.amt_likes%> likes")